import { Playfair_Display, Rubik  } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import styles from '~/scss/_MainLayout.module.scss';

const geistSans = Playfair_Display({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Rubik({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className}`}>
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
